### PR TITLE
Indicate canceled trains and several issue fixes

### LINKED ISSUE #30: Canceled trains are not indicated in the connection API (and nowhere on the website)
This one is in fact 2 bugs.. 

1) When using iRail.be website for a station liveboards, the canceled trains are not shown, while the info is available on the Stations API, see the Android client:

2) this "canceled" information is not shown in the connection API, giving no clue to the user that his train is in fact canceled, which is a huge problem!

id: "0",
departure: {
    delay: "0",
    station: "Tournai",
    stationinfo: {
        id: "BE.NMBS.008885001",
        locationX: "3.396936",
        locationY: "50.613125",
        name: "Tournai",
        standardname: "Tournai"
    },
    time: "1404125820",
    vehicle: "BE.NMBS.IC912",
    platform: "2",
    platforminfo: {
        name: "2",
        normal: "1"
    },
    direction: {
        id: "BE.NMBS.008841608",
        locationX: "5.62235",
        locationY: "50.6604",
        name: "Herstal",
        standardname: "Herstal"
    }
},
arrival: {
    delay: "0",
    station: "Mons",
    stationinfo: {
        id: "BE.NMBS.008881000",
        locationX: "3.942303",
        locationY: "50.45445",
        name: "Mons",
        standardname: "Mons"
    },
    time: "1404127440",
    vehicle: "BE.NMBS.IC912",
    platform: "2",
    platforminfo: {
        name: "2",
        normal: "1"
    },
    direction: {
        id: "BE.NMBS.008841608",
        locationX: "5.62235",
        locationY: "50.6604",
        name: "Herstal",
        standardname: "Herstal"
    }
},
duration: "1620"

screenshot_2014-06-30-12-39-03

### LINKED ISSUE #61: Arrivals don't show stations
The station tag is empty:

http://api.irail.be/liveboard/?format=xml&lang=NL&id=BE.NMBS.008812005&fast=true&arrdep=ARR

### LINKED ISSUE #62: Route data platform incorrect
This is the query: http://api.irail.be/connections/?lang=NL&format=json&to=008814001&from=008895802&sel=depart&date=210515&time=0737

Error is both in XML and JSON, although behaviour is different.

For both the first and the third train there's a platform change for the arrival station if I compare with the website belgianrail.be. For the first route the arrival platform should be platform 10, for the third it should be platform 13.

Both XML and JSON are the same for the first route and don't show any platform change.
For the third route there is a difference:
XML: according to the XML everything is ok: <platform normal="1">12</platform>
JSON: in the JSON blob I can see something is wrong, but not what (normal is zero so something is up, but the platform hasn't changed) :
``` 
				"platform": "12",
				"platforminfo": {
					"name": "12",
					"normal": "0"
				},
```

So anyway, whatever the problem at the server is exactly, there is difference between the output in XML and JSON which shouldn't be. According to the JSON output I suppose that you know the platform has changed and to what it changed.

This is quite an urgent one as we cannot be sure what is correct...

Dirk

### LINKED ISSUE #148: Vehicle stops show arrival time instead of departure time
Vehicle stops show arrival time and delays. This is confusing since NMBS always communicates departure times. As a result vehicle stops time/delays are also different from liveboard departures or connections, where departure time/delays are displayed.
I'd propose to show departure time for `time` and departure delay for `delay`.

### PR DESCRIPTION
**Pull request by jncn**
- Experimental support for cancelled trains for Connections, Liveboard and Vehicle info (Close #30)
- Fix for not updated platforms for Connections and Liveboard (Close #62)
- Fix for empty `departure > station` for Liveboard (Close #61)
- Fix for some delays not showing for Liveboard
- Vehicle stops now display departure time (Close #148)

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Thanks a lot for this @jncn!

A couple of questions before digging into your changes:
 * Is the API still backward compatible?
 * What do you mean by "experimental" support? Is this mergeable?

**Comment by jncn** [comment]
API should be backwards compatible. Only change is the addition of `cancelled` on `Stop` and `DepartureArrival` objects.

Cancelled might need some more testing before I can guarantee it works in all circumstances on all instances. I had only a few real world examples to test. 'Beta' is probably a better description than experimental ;-) I would merge, but we should probably label `cancelled` as beta for this release.

**Comment by pietercolpaert** [comment]
In American English (the English used by programmers), canceled is written with 1 l. Should we correct that? There's no clear rule whether or not to write canceled with 1 or 2 l's afaik...

**Comment by jncn** [comment]
Hmmm, good point I didn't even know there was a difference. I've done some quick research and it seems US public transport carriers use cancelled with two L's:
Delta: http://www.delta.com/content/www/en_US/traveling-with-us/travel-tips-and-tools/delayed-cancelled-flights.html
BART: https://www.bart.gov/news/articles/2015/news20151215
AMTRAK: https://www.amtrak.com/servlet/ContentServer?c=AM_Alert_C&pagename=am/AM_Alert_C/Alerts_Popup&cid=1251627729599
Virgin America: https://www.virginamerica.com/cms/legal/guest-service-commitment

But to me it doesn't really matter, so if you think 'canceled` is better, I'll be happy to change it ;-)

**Comment by jncn** [comment]
Okay, let's use canceled, since this is what GTFS uses too: https://developers.google.com/transit/gtfs-realtime/trip-updates
I'll do the change!

File: api/data/NMBS/liveboard.php [hunk 1]
```diff
@@ -114,22 +114,21 @@ private static function parseData($xml, $time, $lang, $fast = false)
...
             if ($delay == '-') {
                 $delay = '0';
             }
-
-            $platform = '';
-            if (isset($journey['platform'])) {
-                $platform = (string) $journey['platform'];
+            
+            if ($delay == 'cancel') {
+                $delay = 999999; // Indicate something is wrong if `cancelled` is not read by the client
```
Comment (pietercolpaert) [inline api/data/NMBS/liveboard.php]: I find this not a good solution... Without upgrading code, the GUIs will now show a delay of 999999. I believe we should just keep this 0?

File: api/data/NMBS/liveboard.php [hunk 2]
```diff
@@ -139,18 +138,34 @@ private static function parseData($xml, $time, $lang, $fast = false)
...
+            $time = '00d'.(string) $journey['fpTime'].':00';
+            preg_match("/(..)\/(..)\/(..)/si", (string) $journey['fpDate'], $dayxplode);
+            $dateparam = '20'.$dayxplode[3].$dayxplode[2].$dayxplode[1];
+
+            $unixtime = tools::transformtime($time, $dateparam);
+
             if ($fast) {
                 $stationNode = new Station();
-                $stationNode->name = (string) $journey['dir'];
+                $stationNode->name = (string) $journey['targetLoc'];
```
Comment (pietercolpaert) [inline api/data/NMBS/liveboard.php]: Why this change? Should we also include 'dir' as another entity called direction? Might be more interesting than targetLoc in some situations?

File: api/data/NMBS/liveboard.php [hunk 3]
```diff
@@ -114,22 +114,21 @@ private static function parseData($xml, $time, $lang, $fast = false)
...
             if ($delay == '-') {
                 $delay = '0';
             }
-
-            $platform = '';
-            if (isset($journey['platform'])) {
-                $platform = (string) $journey['platform'];
+            
+            if ($delay == 'cancel') {
+                $delay = 999999; // Indicate something is wrong if `canceled` is not read by the client
```
Comment (pietercolpaert) [inline api/data/NMBS/liveboard.php]: I don't like this solution: will break certain GUIs. We should still keep '0' or 'cancel' (wasn't this how it used to be?) here...

File: api/data/NMBS/liveboard.php (hunk 2 above)
Comment (jncn) [inline api/data/NMBS/liveboard.php]: `targetLoc` is always there and has always the same value as `dir`, but the latter is missing if requesting arrivals.

File: api/data/NMBS/liveboard.php (hunk 3 above)
Comment (jncn) [inline api/data/NMBS/liveboard.php]: It used to be 0. Now it will report a delay of ~27 hours. (=99999s)

Comment (pietercolpaert) [inline api/data/NMBS/liveboard.php]: Should be 0 though... 27 hours is just random ;)

Maybe just making it empty? It's not relevant anymore?
